// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pM6GU-IZ6Jbw_JTAg3y-VbaXlQL06kQ',
    appId: '1:575445471242:web:3d1cc4d7afb3a6ebb68ff3',
    messagingSenderId: '575445471242',
    projectId: 'yaa-foods-live-f1774',
    authDomain: 'yaa-foods-live-f1774.firebaseapp.com',
    storageBucket: 'yaa-foods-live-f1774.appspot.com',
    measurementId: 'G-DX0YPG3S91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBinxc0mNZAqpoowO_ai3OZO1couNTjrxA',
    appId: '1:575445471242:android:be9ed09e43f68677b68ff3',
    messagingSenderId: '575445471242',
    projectId: 'yaa-foods-live-f1774',
    storageBucket: 'yaa-foods-live-f1774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlejBQHgcZR4cu94Yp1es0nSI1cuckVIc',
    appId: '1:575445471242:ios:7149f0667dbb74e4b68ff3',
    messagingSenderId: '575445471242',
    projectId: 'yaa-foods-live-f1774',
    storageBucket: 'yaa-foods-live-f1774.appspot.com',
    androidClientId: '575445471242-c15c6hq0ngakmlo7qcr1gk33rfec644e.apps.googleusercontent.com',
    iosClientId: '575445471242-8m96qlr5th9iheebmq5f5gua7o30kopm.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaafoodsDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlejBQHgcZR4cu94Yp1es0nSI1cuckVIc',
    appId: '1:575445471242:ios:7149f0667dbb74e4b68ff3',
    messagingSenderId: '575445471242',
    projectId: 'yaa-foods-live-f1774',
    storageBucket: 'yaa-foods-live-f1774.appspot.com',
    androidClientId: '575445471242-c15c6hq0ngakmlo7qcr1gk33rfec644e.apps.googleusercontent.com',
    iosClientId: '575445471242-8m96qlr5th9iheebmq5f5gua7o30kopm.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaafoodsDriver',
  );
}
